import { reactive } from 'vue';
//console.log(localStorage)
export const store = reactive({
    //routing
    //-------------------
    pages: ['home', 'graph', 'stat'],
    currentPage: 'home',
    contatorePage: 0,
    totaleRisparmi: 0,
    totaleEntrate: 0,
    totaleSpese: 0,
    anno: 23,
    changeGraph: true,
    //-------------------
    data: JSON.parse(localStorage.getItem('myData')),
    mesi: ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'],
    risparmi: {
        23: {
            [1]: 0,
            [2]: 0,
            [3]: 0,
            [4]: 0,
            [5]: 0,
            [6]: 0,
            [7]: 0,
            [8]: 0,
            [9]: 0,
            [10]: 0,
            [11]: 0,
            [12]: 0,
        },
        24: {
            [1]: 0,
            [2]: 0,
            [3]: 0,
            [4]: 0,
            [5]: 0,
            [6]: 0,
            [7]: 0,
            [8]: 0,
            [9]: 0,
            [10]: 0,
            [11]: 0,
            [12]: 0,
        },
        25: {
            [1]: 0,
            [2]: 0,
            [3]: 0,
            [4]: 0,
            [5]: 0,
            [6]: 0,
            [7]: 0,
            [8]: 0,
            [9]: 0,
            [10]: 0,
            [11]: 0,
            [12]: 0,
        },
        26: {
            [1]: 0,
            [2]: 0,
            [3]: 0,
            [4]: 0,
            [5]: 0,
            [6]: 0,
            [7]: 0,
            [8]: 0,
            [9]: 0,
            [10]: 0,
            [11]: 0,
            [12]: 0,
        },
    },

    totaleRisparmioMese: { 23: 0, 24: 0, 25: 0, 26: 0 },
    totaleSpeseMese: { 23: 0, 24: 0, 25: 0, 26: 0 },
    totaleEntrateAnnue: { 23: 0, 24: 0, 25: 0, 26: 0 },
});